# globinclude kitty.d/**/*.conf
shell_integration no-cursor
startup_session none
allow_hyperlinks yes
allow_remote_control yes
editor nvim

font_family JetBrainsMono Nerd Font
bold_font       auto
italic_font     auto
bold_italic_font auto
font_size 16
background_blur 15
background_opacity 0.65
draw_minimal_borders yes
window_padding_width 2
window_border_width 0
hide_window_decorations yes
titlebar-only yes
active_border_color none
cursor_trail 1
cursor_shape                 block
enable_audio_bell            no
repaint_delay                8
input_delay                  2
sync_to_monitor              yes
url_style                    curly
strip_trailing_spaces        smart


tab_bar_edge top
tab_bar_background none
tab_bar_style powerline
tab_powerline_style slanted
tab_title_template "{fmt.fg.c2c2c2}{title}"


map cmd+shift+up neighboring_window up
map cmd+shift+left neighboring_window left
map cmd+shift+right neighboring_window right
map cmd+shift+down neighboring_window down

include onedark.conf

macos_titlebar_color system

map ctrl+f send_text all \x14
map shift+enter send_text all \x1b[13;2u

# Cursor: jump to beginning/end of line
map ctrl+shift+left send_text all \x01
map ctrl+shift+right send_text all \x05
# Alt+Left/Right: jump between words
map alt+left  send_text all \x1bb
map alt+right send_text all \x1bf

# Alt+Shift+Left/Right: beginning/end of line
map alt+shift+left  send_text all \x01
map alt+shift+right send_text all \x05

listen_on unix:/tmp/kitty
