#!/bin/bash

export TEXT_WHITE=0xFFe34b46
export TEXT_GREY=0xff65605d
export TEXT_SPOTIFY_GREEN=0xFF1DB954
export TEXT_RED=0xfffe4f4e
export TEXT_ORGANGE=0xffDFA04B
export BACKGROUND=0xDAfef3c7
export BACKGROUND_DARK=0xff444444
export BACKGROUND_DARKER=0xff222222
export HIGHLIGHT_BACKGROUND=0xFF2aa395
export TRANSPARENT=0x00000000
export BORDER_COLOR=0xFF1a6663

# Base colors (dark to light grays/cyans)
export BASE04=0xFF000a0d
export BASE03=0xFF00161c
export BASE02=0xFF07242b
export BASE01=0xFF58666b
export BASE00=0xFF64737a
export BASE0=0xFF9ca6a9
export BASE1=0xFFa7b3b3
export BASE2=0xFFeeead4
export BASE3=0xFFfef9e2
export BASE4=0xFFffffff

# Yellow shades
export YELLOW=0xFFb39500
export YELLOW100=0xFFfff599
export YELLOW300=0xFFffd500
export YELLOW500=0xFFb39500
export YELLOW700=0xFF665500
export YELLOW900=0xFF332f00

# Orange shades
export ORANGE=0xFFcb6916
export ORANGE100=0xFFffb366
export ORANGE300=0xFFfc7808
export ORANGE500=0xFFcb6916
export ORANGE700=0xFFa25411
export ORANGE900=0xFF5c300a

# Red shades
export RED=0xFFe34b46
export RED100=0xFFff9999
export RED300=0xFFf67673
export RED500=0xFFe34b46
export RED700=0xFFb83d39
export RED900=0xFF571d1b

# Magenta shades
export MAGENTA=0xFFd93091
export MAGENTA100=0xFFff75d4
export MAGENTA300=0xFFf255b6
export MAGENTA500=0xFFd93091
export MAGENTA700=0xFFb02775
export MAGENTA900=0xFF541236

# Violet shades
export VIOLET=0xFF6f67c7
export VIOLET100=0xFFccccff
export VIOLET300=0xFFa79dec
export VIOLET500=0xFF6f67c7
export VIOLET700=0xFF5c54a3
export VIOLET900=0xFF2e2a52

# Blue shades
export BLUE=0xFF2784d2
export BLUE100=0xFFa9d8ff
export BLUE300=0xFF4faeee
export BLUE500=0xFF2784d2
export BLUE700=0xFF1b5e98
export BLUE900=0xFF103656

# Cyan shades
export CYAN=0xFF2aa395
export CYAN100=0xFFb9fffd
export CYAN300=0xFF37e1cd
export CYAN500=0xFF2aa395
export CYAN700=0xFF1a6663
export CYAN900=0xFF103c3b

# Green shades
export GREEN=0xFF849900
export GREEN100=0xFFd1ffad
export GREEN300=0xFFb8fa00
export GREEN500=0xFF849900
export GREEN700=0xFF586600
export GREEN900=0xFF2c3300

# Background/Foreground
export BG=0xFF000a0d
export BG_HIGHLIGHT=0xFF00161c
export FG=0xFF848e91
