[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/workspaces/personal"
desc = "Go Personal"

[[mgr.prepend_keymap]]
on = ["g", "b"]
run = "cd ~/workspaces/beekoff"
desc = "Go Beekoff"

[[mgr.prepend_keymap]]
on = ["g", "l"]
run = "cd ~/workspaces/gl"
desc = "Go GL"

[[mgr.prepend_keymap]]
on = ["g", "b"]
run = "cd ~/workspaces/personal/Brain"
desc = "Go Brain"

[[mgr.prepend_keymap]]
on   = ["z"]
run  = 'plugin zoxide'
desc = "zoxide to a folder"

[[mgr.prepend_keymap]]
on = [ "g", "e" ]
run = "shell 'cursor \"$@\"'"
desc = "Open with Cursor"

[[mgr.prepend_keymap]]
on = [ "g", "f" ]
run = "shell 'open .'"
desc = "Open with Finder"

[[mgr.prepend_keymap]]
on = [ "g", "t" ]
run = "shell 'open -a Kitty .'"
desc = "Open Terminal"

[[mgr.prepend_keymap]]
on   = [ "g", "i" ]
run  = "plugin lazygit"
desc = "run lazygit"


