[[mgr.prepend_keymap]]
on = ["g", "p"]
run = "cd ~/workspaces/personal"
desc = "Go Personal"

[[mgr.prepend_keymap]]
on = ["g", "b"]
run = "cd ~/workspaces/beekoff"
desc = "Go Beekoff"

[[mgr.prepend_keymap]]
on = ["g", "g"]
run = "cd ~/workspaces/gl"
desc = "Go GL"

[[mgr.prepend_keymap]]
on = ["g", "b"]
run = "cd ~/workspaces/personal/Brain"
desc = "Go Brain"

[[mgr.prepend_keymap]]
on = ["u", "a"]
run = "plugin yamb save"
desc = "Add bookmark"

[[mgr.prepend_keymap]]
on = ["u", "g"]
run = "plugin yamb jump_by_key"
desc = "Jump bookmark by key"

[[mgr.prepend_keymap]]
on = ["u", "G"]
run = "plugin yamb jump_by_fzf"
desc = "Jump bookmark by fzf"

[[mgr.prepend_keymap]]
on = ["u", "d"]
run = "plugin yamb delete_by_key"
desc = "Delete bookmark by key"

[[mgr.prepend_keymap]]
on = ["u", "D"]
run = "plugin yamb delete_by_fzf"
desc = "Delete bookmark by fzf"

[[mgr.prepend_keymap]]
on = ["u", "A"]
run = "plugin yamb delete_all"
desc = "Delete all bookmarks"

[[mgr.prepend_keymap]]
on = ["u", "r"]
run = "plugin yamb rename_by_key"
desc = "Rename bookmark by key"

[[mgr.prepend_keymap]]
on = ["u", "R"]
run = "plugin yamb rename_by_fzf"
desc = "Rename bookmark by fzf"
