[tools]
node = "24"
python = "3.14"
go = "1.26"
bun = "1.3.10"
rust = "1.95.0"
pnpm = "11.0.9"
npm = "11.14.1"
"aqua:LuaLS/lua-language-server" = "latest"
"aqua:artempyanykh/marksman" = "latest"
"aqua:tamasfe/taplo" = "latest"
"aqua:bufbuild/buf" = "latest"
"aqua:astral-sh/ruff" = "latest"
"npm:typescript-language-server" = "latest"
"npm:yaml-language-server" = "latest"
"npm:vscode-langservers-extracted" = "latest"
"npm:dockerfile-language-server-nodejs" = "latest"
"npm:pyright" = "latest"
"npm:prettier" = "latest"
"npm:typescript" = "latest"
"npm:@prisma/language-server" = "latest"
"github:jgm/pandoc" = "latest"
"aqua:dandavison/delta" = "latest"

[settings]
experimental = true
