return {
	{ import = "lazyvim.plugins.extras.lsp.none-ls" },
	{ import = "lazyvim.plugins.extras.linting.eslint" },
	{ import = "lazyvim.plugins.extras.formatting.prettier" },
	{ import = "lazyvim.plugins.extras.lang.typescript" },
	{ import = "lazyvim.plugins.extras.lang.json" },
	{ import = "lazyvim.plugins.extras.lang.markdown" },
	{ import = "lazyvim.plugins.extras.lang.rust" },
	{ import = "lazyvim.plugins.extras.lang.tailwind" },
	{ import = "lazyvim.plugins.extras.coding.copilot" },
	-- { import = "lazyvim.plugins.extras.dap.core" },
	-- { import = "lazyvim.plugins.extras.vscode" },
	{ import = "lazyvim.plugins.extras.util.mini-hipatterns" },
	-- { import = "lazyvim.plugins.extras.test.core" },
	-- { import = "lazyvim.plugins.extras.coding.yanky" },
	-- { import = "lazyvim.plugins.extras.editor.mini-files" },
	-- { import = "lazyvim.plugins.extras.util.project" },
}
